package me.yuriisoft.buildnotify.security

import com.intellij.credentialStore.CredentialAttributes
import com.intellij.ide.passwordSafe.PasswordSafe
import com.intellij.openapi.application.PathManager
import com.intellij.openapi.diagnostic.thisLogger
import java.nio.file.Files
import java.nio.file.Path
import java.security.KeyStore
import java.security.MessageDigest
import java.security.SecureRandom
import java.security.cert.X509Certificate
import java.util.concurrent.TimeUnit
import javax.net.ssl.KeyManagerFactory
import javax.net.ssl.SSLContext

/**
 * Auto-generates and persists a self-signed TLS certificate for the WebSocket server.
 *
 * Storage layout under `<IDE config>/buildnotify/`:
 *   - `server.p12` — JKS keystore holding the RSA key pair + self-signed cert
 *   - `password`   — randomly generated keystore password and stored using [PasswordSafe] utility.
 *
 * Certificate generation delegates to the JDK's `keytool` binary (always present in JBR),
 * avoiding any dependency on internal `sun.security.x509` APIs or third-party libraries.
 *
 * On first access (or when the stored keystore is missing/corrupt), a fresh certificate
 * is generated automatically. Advanced users can still override via `keystorePath` in settings.
 */
class AutoGeneratedSslContextProvider : SslContextProvider {

    private val logger = thisLogger()

    private val configDir: Path = Path.of(PathManager.getConfigPath(), CONFIG_SUBDIRECTORY)
    private val keystorePath: Path = configDir.resolve(KEYSTORE_FILENAME)

    /** Always applicable — will generate if missing. */
    override fun isApplicable(): Boolean = true

    override fun provide(): CertificateBundle? =
        runCatching { loadOrGenerate() }
            .onFailure { e -> logger.error("Auto-generated certificate setup failed", e) }
            .getOrNull()

    private fun loadOrGenerate(): CertificateBundle {
        Files.createDirectories(configDir)

        if (Files.isRegularFile(keystorePath)) {
            return runCatching { loadExisting() }
                .onFailure { e ->
                    logger.warn("Stored keystore is corrupt; regenerating: ${e.message}")
                    Files.deleteIfExists(keystorePath)
                }
                .getOrElse { generate() }
        }

        return generate()
    }

    private fun loadExisting(): CertificateBundle {
        val savedPassword = PasswordSafe.instance.getPassword(CREDENTIAL_ATTRIBUTES)
            ?: throw IllegalStateException("Keystore password not found in PasswordSafe")

        val password = savedPassword.toCharArray()
        val keyStore = KeyStore.getInstance(KEYSTORE_TYPE)
        Files.newInputStream(keystorePath).use { keyStore.load(it, password) }

        val cert = keyStore.getCertificate(KEY_ALIAS) as X509Certificate
        cert.checkValidity()

        return CertificateBundle(
            sslContext = buildSslContext(keyStore, password),
            fingerprint = sha256Fingerprint(cert),
        )
    }

    private fun generate(): CertificateBundle {
        logger.info("Generating self-signed TLS certificate via keytool...")

        val password = generatePassword()
        val passwordStr = String(password)

        runKeytool(
            "-genkeypair",
            "-alias", KEY_ALIAS,
            "-keyalg", KEY_ALGORITHM,
            "-keysize", KEY_SIZE.toString(),
            "-sigalg", SIGNATURE_ALGORITHM,
            "-validity", VALIDITY_DAYS.toString(),
            "-storetype", KEYSTORE_TYPE,
            "-keystore", keystorePath.toAbsolutePath().toString(),
            "-storepass", passwordStr,
            "-keypass", passwordStr,
            "-dname", DNAME,
        )

        PasswordSafe.instance.setPassword(CREDENTIAL_ATTRIBUTES, passwordStr)

        val keyStore = KeyStore.getInstance(KEYSTORE_TYPE)
        Files.newInputStream(keystorePath).use { keyStore.load(it, password) }

        val cert = keyStore.getCertificate(KEY_ALIAS) as X509Certificate
        logger.info("Certificate stored at $keystorePath (valid until ${cert.notAfter})")

        return CertificateBundle(
            sslContext = buildSslContext(keyStore, password),
            fingerprint = sha256Fingerprint(cert),
        )
    }

    // ── companion ────────────────────────────────────────────────────────────

    private companion object {
        const val CONFIG_SUBDIRECTORY = "buildnotify"
        const val KEYSTORE_FILENAME = "server.p12"
        const val KEYSTORE_TYPE = "PKCS12"
        const val KEY_ALIAS = "buildnotify"
        const val KEY_ALGORITHM = "RSA"
        const val KEY_SIZE = 2048
        const val SIGNATURE_ALGORITHM = "SHA256withRSA"
        const val VALIDITY_DAYS = 3650
        const val PASSWORD_LENGTH = 32
        const val KEYTOOL_TIMEOUT_SEC = 30L
        const val DNAME = "CN=BuildNotify, O=BuildNotify Plugin, L=Local"

        val CREDENTIAL_ATTRIBUTES = CredentialAttributes(
            serviceName = "BuildNotifyPlugin",
            userName = "keystore_password",
        )

        fun buildSslContext(keyStore: KeyStore, password: CharArray): SSLContext {
            val kmf = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm())
            kmf.init(keyStore, password)
            return SSLContext.getInstance("TLS").apply { init(kmf.keyManagers, null, null) }
        }

        fun sha256Fingerprint(cert: X509Certificate): String =
            MessageDigest.getInstance("SHA-256")
                .digest(cert.encoded)
                .joinToString(":") { "%02X".format(it) }

        fun generatePassword(): CharArray {
            val random = SecureRandom()
            val chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
            return CharArray(PASSWORD_LENGTH) { chars[random.nextInt(chars.length)] }
        }

        fun resolveKeytool(): Path {
            val javaHome = Path.of(System.getProperty("java.home"))
            val isWindows = System.getProperty("os.name").lowercase().contains("win")
            val executable = if (isWindows) "keytool.exe" else "keytool"
            val keytool = javaHome.resolve("bin").resolve(executable)
            require(Files.isExecutable(keytool)) {
                "keytool not found at $keytool (java.home=$javaHome)"
            }
            return keytool
        }

        fun runKeytool(vararg args: String) {
            val keytool = resolveKeytool()
            val command = listOf(keytool.toAbsolutePath().toString()) + args

            val process = ProcessBuilder(command)
                .redirectErrorStream(true)
                .start()

            val completed = process.waitFor(KEYTOOL_TIMEOUT_SEC, TimeUnit.SECONDS)
            val output = process.inputStream.bufferedReader().readText().trim()

            if (!completed) {
                process.destroyForcibly()
                throw IllegalStateException("keytool timed out after ${KEYTOOL_TIMEOUT_SEC}s")
            }

            val exitCode = process.exitValue()
            if (exitCode != 0) {
                throw IllegalStateException("keytool failed (exit=$exitCode): $output")
            }
        }
    }
}