package me.yuriisoft.buildnotify.security

import com.intellij.openapi.components.Service
import com.intellij.openapi.components.service
import com.intellij.openapi.diagnostic.thisLogger
import me.yuriisoft.buildnotify.settings.PluginSettingsState
import javax.net.ssl.SSLContext

/**
 * Selects and caches the appropriate [SslContextProvider].
 *
 * Priority:
 *   1. [UserProvidedSslContextProvider]  — when keystore path + password env var are present
 *   2. [AutoGeneratedSslContextProvider] — fallback, always applicable
 */
@Service(Service.Level.APP)
class CertificateManager {

    private val logger = thisLogger()

    @Volatile
    private var cached: CertificateBundle? = null

    fun sslContext(): SSLContext? = bundle()?.sslContext

    fun fingerprint(): String? = bundle()?.fingerprint

    /** Invalidates the cache — useful when settings change at runtime. */
    fun invalidate() {
        cached = null
    }

    private fun bundle(): CertificateBundle? {
        cached?.let { return it }

        synchronized(this) {
            cached?.let { return it }
            return resolveBundle().also { cached = it }
        }
    }

    private fun resolveBundle(): CertificateBundle? {
        val settings = service<PluginSettingsState>().snapshot()
        val providers = listOf(
            UserProvidedSslContextProvider(settings),
            AutoGeneratedSslContextProvider(),
        )

        for (provider in providers) {
            if (!provider.isApplicable()) continue
            val bundle = provider.provide()
            if (bundle != null) {
                logger.info("TLS configured via ${provider::class.simpleName}")
                return bundle
            }
            logger.warn("${provider::class.simpleName} was applicable but failed — trying next")
        }

        logger.error("All SSL providers failed — WebSocket will run without TLS")
        return null
    }

    companion object {
        @JvmStatic
        fun getInstance(): CertificateManager = service()
    }
}