package me.yuriisoft.buildnotify.security

import com.intellij.openapi.components.Service
import com.intellij.openapi.components.service
import com.intellij.openapi.diagnostic.thisLogger
import me.yuriisoft.buildnotify.settings.PluginSettingsState
import javax.net.ssl.SSLContext

@Service(Service.Level.APP)
class CertificateManager {

    private val logger = thisLogger()

    @Volatile
    private var cached: CertificateBundle? = null

    fun sslContext(): SSLContext? = bundle()?.sslContext

    fun fingerprint(): String? = bundle()?.fingerprint

    /**
     * Exposes the full [CertificateBundle] for consumers that need both
     * the [SSLContext] and the raw [javax.net.ssl.KeyManager]s (e.g.
     * [me.yuriisoft.buildnotify.network.server.MtlsWebSocketServerFactory]).
     *
     * `internal` visibility — intentionally not part of the public API.
     */
    internal fun bundle(): CertificateBundle? {
        cached?.let { return it }
        synchronized(this) {
            cached?.let { return it }
            return resolveBundle().also { cached = it }
        }
    }

    fun invalidate() {
        cached = null
    }

    private fun resolveBundle(): CertificateBundle? {
        val settings = service<PluginSettingsState>().snapshot()
        val providers = listOf(
            UserProvidedSslContextProvider(settings),
            AutoGeneratedSslContextProvider(),
        )

        for (provider in providers) {
            if (!provider.isApplicable()) continue
            val bundle = provider.provide()
            if (bundle != null) {
                logger.info("TLS configured via ${provider::class.simpleName}")
                return bundle
            }
            logger.warn("${provider::class.simpleName} was applicable but failed — trying next")
        }

        logger.error("All SSL providers failed — WebSocket will run without TLS")
        return null
    }

    companion object {
        @JvmStatic
        fun getInstance(): CertificateManager = service()
    }
}