package me.yuriisoft.buildnotify.security

import com.intellij.openapi.diagnostic.thisLogger
import me.yuriisoft.buildnotify.settings.PluginSettingsState
import java.io.InputStream
import java.nio.file.Files
import java.nio.file.Path
import java.security.KeyStore
import java.security.MessageDigest
import java.security.cert.X509Certificate
import javax.net.ssl.KeyManager
import javax.net.ssl.KeyManagerFactory
import javax.net.ssl.SSLContext

/**
 * Loads a TLS certificate from a user-provided JKS keystore.
 *
 * Configuration:
 *   - keystore path  → [PluginSettingsState] `keystorePath`  OR  env `BUILDNOTIFY_KEYSTORE_PATH`
 *   - password       → env `BUILDNOTIFY_KEYSTORE_PASSWORD`
 *
 * Phase 2 change: [CertificateBundle.keyManagers] is now populated — see
 * [AutoGeneratedSslContextProvider] for the rationale.
 */
class UserProvidedSslContextProvider(
    private val settings: PluginSettingsState.State,
) : SslContextProvider {

    private val logger = thisLogger()

    override fun isApplicable(): Boolean =
        password() != null && resolveKeystoreStream() != null

    override fun provide(): CertificateBundle? {
        val password = password() ?: return null
        val stream = resolveKeystoreStream() ?: return null

        return stream.use { keystoreStream ->
            runCatching {
                val keyStore = KeyStore.getInstance("JKS")
                keyStore.load(keystoreStream, password)

                val cert = keyStore.getCertificate(KEY_ALIAS) as X509Certificate
                val keyManagers = buildKeyManagers(keyStore, password)

                CertificateBundle(
                    sslContext = buildSslContext(keyManagers),
                    fingerprint = sha256Fingerprint(cert),
                    keyManagers = keyManagers,
                )
            }
                .onFailure { e -> logger.error("Failed to load user-provided keystore", e) }
                .getOrNull()
        }
    }

    private fun password(): CharArray? =
        System.getenv("BUILDNOTIFY_KEYSTORE_PASSWORD")?.toCharArray()

    private fun resolveKeystoreStream(): InputStream? {
        val envPath = System.getenv("BUILDNOTIFY_KEYSTORE_PATH")
        val settingsPath = settings.keystorePath.trim().takeIf { it.isNotEmpty() }
        val path = envPath ?: settingsPath ?: return null
        val file = Path.of(path)
        if (!Files.isRegularFile(file) || !Files.isReadable(file)) return null
        return Files.newInputStream(file)
    }

    private companion object {
        const val KEY_ALIAS = "buildnotify"

        fun buildKeyManagers(keyStore: KeyStore, password: CharArray): Array<KeyManager> {
            val kmf = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm())
            kmf.init(keyStore, password)
            return kmf.keyManagers
        }

        fun buildSslContext(keyManagers: Array<KeyManager>): SSLContext =
            SSLContext.getInstance("TLS").apply {
                init(keyManagers, null, null)
            }

        fun sha256Fingerprint(cert: X509Certificate): String =
            MessageDigest.getInstance("SHA-256")
                .digest(cert.encoded)
                .joinToString(":") { "%02X".format(it) }
    }
}